updated fastify version
gj/fastify-ws pull request #10
Opened 2019-02-27 14:06 UTC by imrefazekas

2019-02-27 15:20 UTC, gj reviewed
Hey @imrefazekas — thanks for the contribution!

I'll test this out after work today.

2019-02-27 15:20 UTC, gj commented on index.js
> +  fastify: '>=1.x',
I think I'd feel better about not making this quite so open-ended. What are your thoughts?

2019-02-27 15:20 UTC, gj commented on package.json
> +    "fastify": "^2.0.0",
I wonder if we should change this to something like `"fastify": "1.7.0 - 2"` to bring these package bumps to users of Fastify 1.x as well. If there's no breaking change with the Fastify API that we're interfacing with (need to test this out later), I think I'd prefer to maintain compatibility.

2019-02-28 10:25 UTC, imrefazekas commented
Pls merge and publish if it works fine. It is working in my app using my branch...
Thanks!

2019-02-28 14:23 UTC, gj requested changes
Would like to nail down the version compat a bit tighter, but once these changes are in I'll merge and publish. Thanks again for the contribution @imrefazekas !

2019-02-28 14:23 UTC, gj commented on index.js
> +  fastify: '>=1.x',
```suggestion
  fastify: '1.7.0 - 2',
```

2019-02-28 14:23 UTC, gj commented on package.json
> +  "version": "1.0.1",
I'll bump the package version in a separate commit
```suggestion
  "version": "1.0.0",
```

2019-02-28 14:23 UTC, gj commented on package.json
> +    "fastify": "^2.0.0",
```suggestion
    "fastify": "1.7.0 - 2",
```

2019-03-04 23:22 UTC, merged